Instabug/Instabug-React-Native

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
Missing to be bridge for android since the iOS lib is already doing it and the react-native js module is exposing it.
https://github.com/Instabug/instabug-reactnative/blob/master/index.js#L397
> React native js bridge for setAttachmentTypesEnabled instabug method

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
This PR fixes
> TypeError: undefined is not a function (evaluating 'Instabug.IBGLog(log)')
at `Instabug.IBGLog("test")` invocation.
> Rename log to IBGLog in Android module

- index.js
Having a `// @flow` comment in the file without annotations will throw flow errors
> Remove flow annotation

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativePackage.java
React Native 0.47 has removed the `createJSModules` method. Had to remove the `@Override` to make the lib compatible with that version of RN.
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
> 0.47 backward compatibile Android support

- ios/RNInstabug/InstabugReactBridge.m
The "logOut" method should be exposed with the same name in both iOS and Android. Currently it is necessary to write platform specific JS code to handle both cases. This PR renames the iOS exposed 'logout' method to 'logOut' to match Android.
This would be a breaking change for future iOS versions. The method could be overloaded to provide backward compatibility. I'd be happy to update this PR in that case.
> Rename iOS exported method 'logout' to 'logOut' to match Android implementation

- ios/RNInstabug/InstabugReactBridge.m
This removes the need to access `va_list` in a non-variadic function.
By adding a variadic logging function, we can still bridge `RCTLogFunction`, without changing the public API of `IBGNSLogWithLevel` to not require a `va_list`.
This also removes the need to call the log function on the main queue, which was applied in #76 (7cc7e90a5a49629519706942334c9e6e9957e628).
Fixes #82
> Fix bad access to null variadic args

- link.rb
Fix to #86 
Dunno if this should be done to `unlink.rb` as well. Ping me if that should be done as well.
> Add framework path to all build configurations

- ios/RNInstabug/InstabugReactBridge.m
Since RN 0.49, `requiresMainQueueSetup` needs to be defined if the module overrides `constantsToExport`.
> Add requiresMainQueueSetup method

- ios/RNInstabug/InstabugReactBridge.m
Recommend merging this quickly. The isRunningLive feature is effectively broken for the RN -> iOS integration. It will always return true.
> Fix isRunningLive always returning true on device

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
When calling `setInvocationEvent()` in javascript, this message gets sent across the bridge on a non-ui thread. The native instabug internal Android code eventually touches the UI view hierarchy, which cannot be touched by a non-UI thread... 
This PR simply executes this internal method on the UI thread.
> Android crashes when calling setInvocationEvent() from Javascript

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativePackage.java
By default, the Instabug React Native Android SDK will enable crash reporting, which will set the default thread exception handler... If I want to use a different crash handler, I have no option of disabling this, until my javascript code executes `Instabug.setCrashReportingEnabled(false);
`. This means that there are potentially a few seconds of critical startup time where crashes will be sent to instabug. 
This PR lets the developer opt out of crash reporting when initializing the Instabug React Native package.
> Allow RN package initialization to configure crash reporting

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativePackage.java
The Android implementation is missing a branch in the `parseInvocationEvent` loop for the `InstabugInvocationEvent.SCREENSHOT` type. It prevents users from using the screenshot invocation on Android React Native apps.
> parse screenshot invocation event type

- index.js
- modules/BugReporting.js
- modules/Chats.js
- modules/CrashReporting.js
- modules/FeatureRequests.js
- modules/Replies.js
- modules/Surveys.js
- utils/InstabugUtils.js
Webpack disallows accessing `module.exports` from within es6 files, e.g.
where `import` is used. This assignment results in:
"Attempted to assign to readonly property"
https://github.com/webpack/webpack/issues/3491
> Don't mix import and module.exports

- index.js
- modules/CrashReporting.js
- utils/InstabugUtils.js
And make use of that ability in the library. Sensible because Utils is
not a meaningful collection.
I broke destructuring in #257 due to an incorrect understanding of how default exports work.
https://github.com/Instabug/Instabug-React-Native/pull/257#issuecomment-475310926
> Restore ability to destructure InstabugUtils

- CHANGELOG.md
- README.md
- package.json
- utils/XhrNetworkInterceptor.js
* Fixes an issue that causes the sdk to crash when a network request has no headers.
> 📝 fix network log request headers crash

- .circleci/config.yml
- CHANGELOG.md
- android/build.gradle
- android/upload_sourcemap.sh
- autolink.rb
- instabug-reactnative.podspec
- ios/RNInstabug/InstabugReactBridge.m
- ios/upload_sourcemap.sh
* Fixes an issue when causing duplicate framework when using cocoapods
* Fixes an issue that cause a deadlock when calling `concole.log` many times after `Instabug.startWithToken`
* Fixes an issue in the upload sourcemap script that was preventing it from greping the token automatically
* Fixes an issue that caused Android release builds to fail when building on a Windows machine.
> 📝 8.5.0 bug fixes

- __tests__/index.spec.js
- index.d.ts
- index.js
- modules/BugReporting.js
- modules/Surveys.js
- Move constants to a single shared file
- Use the class `IBGEventEmitter` to handle all JS events.
> 🔨 refactor js code

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- index.js
- ios/RNInstabug/InstabugReactBridge.m
- Fixed string mapping for addVideoMessage in iOS in accordance with the
existing Android key.
- Fixed string mapping for conversationsHeaderTitle.
> Fix/string mappings in iOS

- ios/RNInstabug/InstabugReactBridge.m
`IBGpreSendingHandler` event was accidentally removed while refactoring modules.
Added `IBGpreSendingHandler` to the supported events of `InstabugReactBridge`.
> 🐛 Add IBGpreSendingHandler to the supported events

- index.js
We reject empty string values to be passed to the second argument.
- Discard the responsible validation statement.
- Although the discarded statement also checks for `null` and `undefined` values besides empty string values, we don't need to add a replacement because the subsequent validation statement i.e. `typeof value !== 'string'` already invalidates these values.
> 🐛 Allow empty string to be passed to setUserAttribute value

- index.d.ts
`color` is a string, not a number.
> Fix type for setPrimaryColor

- android/build.gradle
The previous boolean expression for checking the `instabugUploadEnable` always returned true even if the `instabugUploadEnable` ext property was set to `false`. I must confess that either I'm currently too tired, or I don't know enough to understand why this was happening.
Adding the parentheses fixes it. I manually tested all the cases:
* Not adding the `instabugUploadEnable` property: Source map is **uploaded**
* Adding the `instabugUploadEnable` property with true as value: Source map is **uploaded**
* Adding the `instabugUploadEnable` property with false as value: Source map is **not uploaded**
> Fix android build ignoring `instabugUploadEnable` property

- CHANGELOG.md
- __tests__/crashReporting.spec.js
- __tests__/index.spec.js
- index.js
- jest/mockInstabugUtils.js
- modules/BugReporting.js
- modules/CrashReporting.js
- utils/InstabugUtils.js
* minor changes to remove cycle warnings
> Fixing cycle warnings

- CHANGELOG.md
- android/upload_sourcemap.sh
- ios/upload_sourcemap.sh
* Removes the extra single quotations after greping the token.
> Fixing automatic soucemap upload script

- CHANGELOG.md
- InstabugSample/ios/InstabugSampleTests/InstabugBugReportingTests.m
- ios/RNInstabug/InstabugBugReportingBridge.h
- ios/RNInstabug/InstabugBugReportingBridge.m
- package.json
* Fixes `BugReporting.setViewHierarchyEnabled` crashing on iOS due to a typo
> `BugReporting.setViewHierarchyEnabled` Hotfix

- CHANGELOG.md
- android/upload_sourcemap.sh
- package.json
https://instabug.atlassian.net/browse/INSD-3904
Fixes a typo in `upload_sourcemap.sh` that caused the version name not to be uploaded.
> 🐛 Fix version name uploading on Android [INSD-3904]

- CHANGELOG.md
- utils/XhrNetworkInterceptor.js
Fixes an issue where XHR Response is not being logged.
> [Hotfix] Network Logging - Include XHR Response when responseType is `""`

- index.d.ts
In order to fix https://github.com/Instabug/Instabug-React-Native/issues/498 Issue.
A missing function in index.d.ts has been added.
> [FIX] adding OnNavigationStatusChange into index.d.ts

- .circleci/config.yml
- __tests__/index.spec.js
- index.js
- `setSdkDebugLogsLevel` API is targeted for iOS only, calling it on Android would crash the app. I've added a platform check to avoid that.
- Disable node_modules cache on test_module job.
> Fix setSdkDebugLogsLevel crashing on Android

- index.d.ts
We had an older API called logUserEventWithNameAndParams that was removed a while back, however its TS spec got mixed with the existing one, and now the developer IDE would show logUserEventWithName with the older signature. I’ve updated the TS spec which eliminates the confusion.
> Update TS spec for logUserEventWithName

- InstabugSample/App.js
- README.md
Replaces the usage of the deprecated API `Instabug.startWithToken` with the newer API `Instabug.start`.
> Replace deprecated API in Sample App [MOB-4792]

- __tests__/xhrNetworkInterceptor.spec.js
- utils/XhrNetworkInterceptor.js
- Added a type check on the request body of a network log in the `NetworkLogger.js` module.
- Stringified the request body in case it's not a string before passing it to the native layer.
- Adjusted unit tests accordingly.
> [INSD-5139] Fix handling a network request body that is not a string

- android/upload_sourcemap.sh
Fixed grep commands in android sourcemap upload script
> [MOB-5167] Fix grep commands in android sourcemap upload script

- .circleci/config.yml
- Fix `working_directory` invalid value.
- Rollback Xcode version for compatibility with _Escape_ build process.
> [MOB-5219] Fix CI publish script

- CHANGELOG.md
- utils/XhrNetworkInterceptor.js
> Fixed response headers being logged incorrectly if their value contains the ":" separator
> Fix network response header value logging

- .npmignore
Open to see what was bundled: https://unpkg.com/browse/instabug-reactnative@10.11.0/
**To test:**
```sh
npm pack --dry-run
```
> [MOB-8367] Stop publishing useless files

- __tests__/index.spec.js
- index.js
- jest/mockInstabugUtils.js
- utils/InstabugUtils.js
> Added defensive type checking code to logError function to prevent crashes due to inputting non-string values to it.
> [INSD-6706] Add defensive type checking to logError

- ios/RNInstabug/RCTConvert+InstabugEnums.h
Could not upgrade to expo 44 because iOS build was failing.
As explained here: expo/expo#15622 (comment)
Old style imports are not supported anymore from expo 44.
> [MOB-7935] Favor namespaced import of React/RCTConvert.h

- InstabugSample/__tests__/instabugUtils.spec.js
- __tests__/crashReporting.spec.js
- modules/CrashReporting.js
- utils/InstabugUtils.js
> In a Crash Report, the exception JSON object has a parameter `message` that was a combination between `name` and `message` of the exception. This PR splits this parameter into `e_name` and `e_message` .
> [IBGCRASH-9968] Split CR exception message parameter

- index.d.ts
- Fix the return type of `APM.startExecutionTrace` to be `Promise<Trace>` instead of `Trace`. 
https://github.com/Instabug/Instabug-React-Native/issues/684
> [MOB-8620] Fix startExecutionTrace return type

- ios/RNInstabug/InstabugReactBridge.m
- ios/RNInstabug/RCTConvert+InstabugEnums.m
- Fix a typo in the ```dismissTypeAddAttachment``` enum constant in iOS bridge
> [MOB-8633] Fix typo in dismissType enum in iOS bridge

- android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- Add string keys for the ```dismissType``` enum values on Android
> [MOB-8642] Map dismissType enum values on Android

- CHANGELOG.md
- InstabugSample/android/app/src/main/java/com/instabugsample/MainApplication.java
- README.md
- __tests__/index.spec.js
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativePackage.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java
- index.d.ts
- index.js
- package.json
Use Instabug.start to initialize SDK from JS without any extra native code on Android.
> [MOB-8866] Start SDK from JS only

- android/upload_sourcemap.sh
Android build process fails on the upload_sourcemap step, producing the following error:
```bash
./upload_sourcemap.sh: line 102: syntax error near unexpected token `fi'
./upload_sourcemap.sh: line 102: `fi'
...
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':instabug-reactnative:upload_sourcemap'.
> Process 'command 'sh'' finished with non-zero exit value 2
```
Upon closer inspection, it was found that there was one too many `fi` tokens in the bash script, meaning that the final line of the script was an unmatched `fi` (hence the error). This PR removes the additional token to ensure that the script runs without error.
> [MOB-8883] Fix Android upload_sourcemap.sh

- .circleci/config.yml
- android/upload_sourcemap.sh
- Add CI job to validate shell files
- Fix Android shell script error
- Fix e2e_android flaky runs due to low resources
> [MOB-8883] Add CI job to validate shell files and increase e2e_android resources

- .circleci/config.yml
- .github/dependabot.yml
- CHANGELOG.md
- __tests__/networkLogger.spec.js
- __tests__/xhrNetworkInterceptor.spec.js
- android/upload_sourcemap.sh
- package.json
- react-native.config.js
* Fixes an issue with network responses of type JSON not getting logged
* Fixes an issue that may cause the android build to fail
* Fixes an issue with iOS autolinking that causes the user local path to be referenced in xcode
> [MOB-8891] Release/11.0.1

- .circleci/config.yml
- InstabugSample/android/gradle.properties
- Increase java max heap size.
- Clean up ci config from the unused context
> [MOB-6504] Fix android ci oom

- .circleci/config.yml
- InstabugSample/.detoxrc.json
- InstabugSample/package.json
- Bumps xcode version to v13.4.1 for `test_ios`, `e2e_ios` and `publish` jobs
- Bumps Detox version to v19.8.4
> [MOB-9109] Bump deprecated Xcode versions for affected CI jobs

- .circleci/config.yml
- InstabugSample/metro.config.js
- InstabugSample/package.json
- InstabugSample/yarn.lock
- package.json
Symlinks the Instabug SDK in the sample app's `node_modules` instead of copying the whole Instabug-React-Native repo files again in the `node_modules` folder.
- Update SDK files on the fly (no need to `yarn install` every time you do a change) with hot reload when running the sample app.
- Update native SDK code in the sample app's Android and iOS projects — This makes autosuggestions in Android Studio and Xcode much better.
- More efficient storage usage — No need to copy the whole repo each time you install, it also prevents recursive file copying when doing multiple installs.
> [MOB-9131] Symlink the SDK in the sample app

- InstabugSample/yarn.lock
- yarn.lock
The `yarn.lock` files got out of syncduring recent changes:
1. Package's lockfile: got out of sync after #675, since we never run `yarn` in the root directory but always in the example directory.
1. Example's lockfile: got out of sync after #743 where detox version changed in `package.json` but not `yarn.lock`.
> [MOB-9931] Sync `yarn.lock` files

- CHANGELOG.md
- android/upload_sourcemap.sh
Disable minification in Hermes source maps generation script by adding the argument `--minify false`
> [MOB-9965] Fix Hermes source maps script on Android

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
These APIs were removed by mistake in #699 while rebasing it on #704.
> [MOB-9975] Call Missing Android APIs in `start`

- InstabugSample/App.js
This method was deprecated and then removed in #703, so it crashes the sample app when you press the "SEND BUG REPORT" button, for that, I changed it to the current version of it, `BugReporting.show`.
> [MOB-9974] Resolve deprecated API calls in the sample app

- .circleci/config.yml
Make sure that files like `yarn.lock` and `project.pbxproj` are in sync with the latest changes in `package.json` and `ios/upload_sourcemap.sh` files respectively.
This job helps catch out of sync changes early on.
These are PRs that would not be neseccariy anymore after merging this: 
- #746 
- #747 
- #752 
> [MOB-9980] Add `sync_generated_files` CI Job

- src/modules/APM.js
- src/modules/BugReporting.js
- src/modules/FeatureRequests.js
- src/modules/Instabug.js
- src/utils/ArgsRegistry.js
- typescript_validator.js
Creating a SSOT for enums in JS, has a some of benefits:
1. Removes duplicate definitions.
1. Eases sync with native `ArgsRegistry`.
1. Declutters Modules files.
> [MOB-10149] Extract enums to `ArgsRegistry`

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugBugReportingModule.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
Users face a compile error on Android stating that `local variables accessed from within inner class need to be declared final`. This is only encountered on projects with Java version prior to 8. 
**Starting Java 8**, this requirement was relaxed to final or _effectively final_. A variable whose value is never changed after it is initialized is effectively final. Hence, users on Java 8 or higher do not face this issue. 
Declare these local variables _explicitly_ `final` so that the app builds successfully on different Java versions. 
> [INSD-8104] Declare local vars final

- package.json
- test/apm.spec.js
- test/bugReporting.spec.js
- test/crashReporting.spec.js
- test/featureRequests.spec.js
- test/instabug.spec.js
- test/jest/mockAPM.js
- test/jest/mockFeatureRequests.js
- test/jest/mockInstabug.js
- test/networkLogger.spec.js
- test/replies.spec.js
- test/report.spec.js
- test/surveys.spec.js
All the mocks in our SDK were written twice, once in Jest and once Sinon.
Since Jest is our main test runner and it provides powerful mocking mechanisms, we ditched Sinon mocks (except for XHR mocks) in favor of Jest mocks, this makes our code less redundant.
> [MOB-10117] Migrate Sinon Mocks to Jest

- tests/utils/InstabugUtils.spec.js
Enables and fixes the "should emit event IBGSendUnhandledJSCrash when platform is android and onReportSubmitHandler is set" `InstabugUtils` disabled test.
> [MOB-10372] Enable Disabled `InstabugUtils` Test

- package.json
- tests/mocks/fakeNetworkRequest.js
- tests/setup.js
- tests/utils/XhrNetworkInterceptor.spec.js
- yarn.lock
Migrates `Sinon`'s fake/mock `XMLHttpRequest` to Nock request mocking and a Node XHR polyfill (`xhr2`).
> [MOB-10381] Migrate Sinon's fake XHR to Nock and XHR polyfill

- CHANGELOG.md
- android/gradle.properties
- Removes the single quotes around `buildToolsVersion` value in `gradle.properties`, which causes `Invalid revision: '30.0.2'` error when building the project in Android Studio.  
> [MOB-10423] Fix `Invalid revision` error

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugBugReportingModule.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugBugReportingModuleTest.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java
- example/ios/InstabugSampleTests/InstabugBugReportingTests.m
- example/ios/InstabugSampleTests/InstabugSampleTests.m
- ios/RNInstabug/InstabugBugReportingBridge.h
- ios/RNInstabug/InstabugBugReportingBridge.m
- ios/RNInstabug/InstabugReactBridge.h
- ios/RNInstabug/InstabugReactBridge.m
- src/modules/BugReporting.ts
- src/modules/Instabug.ts
- tests/mocks/mockBugReporting.js
- tests/mocks/mockInstabug.js
- tests/modules/BugReporting.spec.js
- tests/modules/Instabug.spec.js
1. Adds `BugReporting.setDisclaimerText` API
2. Adds `BugReporting.setCommentMinimumCharacterCount` API
3. Deprecates `Instabug.enable` and `Instabug.disable` APIs in favour of a new API `Instabug.setEnabled`, which works on both platforms
4. Adds unit tests for the new APIs
**Usage Examples:** 🚀 
1. 
```
BugReporting.setDisclaimerText(
"Instabug can help developers produce more quality code. [Learn more](https://www.instabug.com)"); 
```
2. 
`BugReporting.setCommentMinimumCharacterCount(20);`
Another usage:
```
BugReporting.setCommentMinimumCharacterCount(20, [
BugReporting.reportType.bug,
BugReporting.reportType.feedback,
]);
```
3. `Instabug.setEnabled(true);` OR `Instabug.setEnabled(false);`
> [MOB-10611] Add new APIs

- CHANGELOG.md
- src/index.ts
**Problem:**
In `index.js`, we import `Survey` interface with `import type` while re-export it as `export { Survey };` which causes a build error with certain babel versions. 
**Solution:**
Re-export `Survey` interface as `export type { Survey };`
> [INSD-8643] Fix `Survey` interface export

- CHANGELOG.md
- example/src/screens/HomeScreen.js
- src/modules/CrashReporting.ts
- tests/modules/CrashReporting.spec.js
**Problem:**
Enforcing a strong type for `reportJSException` would require code changes from the users as the `catch` block parameter has to be of type `any` / `unknown`.
**Solution:**
1. Instead of the users having to handle the `error` type checking before calling the API, we accept `any` type and handle the type checking internally not to cause breaking changes with the current API.
2. Introduce a new strongly typed API `reportError` and deprecate `reportJSException`
> [INSD-8643] Add `reportError` and deprecate `reportJSException`

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java
- ios/RNInstabug/ArgsRegistry.m
- src/utils/ArgsRegistry.ts
1. Add these string keys: `screenRecording`, `insufficientContentMessage`, and `insufficientContentTitle` with their mapping on both platforms (if relevant).
2. For already-existing keys on one platform, we add the corresponding mapping on the other platform (if relevant) for consistency and unification. 
Note:
This is based on an internal snapshot, so the Android tests are expected to fail until we bump to the Android release, including the new keys.
To-Do:
Rebase the PR after bumping the Android version
> [MOB-10648] Add Overridable String Keys

- CHANGELOG.md
- src/modules/Instabug.ts
> [MOB-11436] Deprecate `callPrivateApi`

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- example/ios/InstabugSampleTests/InstabugSampleTests.m
- ios/RNInstabug/InstabugReactBridge.h
- ios/RNInstabug/InstabugReactBridge.m
- src/index.ts
- src/models/InstabugConfig.ts
- src/modules/APM.ts
- src/modules/Instabug.ts
- src/utils/ArgsRegistry.ts
- src/utils/Enums.ts
- tests/modules/Instabug.spec.js
- Add `debugLogsLevel` optional property to `InstabugConfig` and its native mappings.
- Add `LogLevel` enum
- Deprecate the APIs:
1. `Instabug.setDebugEnabled`
2. `Instabug.setSdkDebugLogsLevel`
3. `APM.setLogLevel`
- Deprecate the enums `sdkDebugLogsLevel` and `logLevel`
> [MOB-11440] Add `debugLogsLevel` to `InstabugConfig`

- CHANGELOG.md
- src/utils/InstabugUtils.ts
The original global error handler was initialized in the global scope, so it used to have the default value set by React Native. When users try to set a global error handler themselves, the handler will be ignored, due to the early initialization of `originalHandler`.
This PR fixes this issue by getting the global error handler within `Instabug.init` scope. Allowing the users to set global error handlers before initializing Instabug. Setting handlers after Instabug's initialization would still not be possible.
```js
// This handler will be called before Instabug's global error handler
ErrorUtils.setGlobalHandler((err, isFatal) => {
console.error("Something bad happened");
});
Instabug.init({ ... });
```
> [MOB-11562] Fix Original Error Handler Not Called

- CHANGELOG.md
- src/modules/Instabug.ts
This API works only on iOS with no equivalent on Android, which makes it confusing to users. We should deprecate it and recommend managing and checking app running environment using environment variables instead.
> [MOB-11609] Deprecate `Instabug.isRunningLive` API

- CHANGELOG.md
- android/build.gradle
Allow users to use Instabug Android SDK within their Java/Kotlin files.
> [MOB-11894] Export Native Android SDK

- CHANGELOG.md
- RNInstabug.podspec
- example/ios/Podfile.lock
> [MOB-11697] Bump iOS SDK to `v11.7.0`

- CHANGELOG.md
- example/src/App.tsx
- example/src/screens/BugReportingScreen.tsx
- example/src/screens/SettingsScreen.tsx
- src/index.ts
- src/models/InstabugConfig.ts
- src/modules/BugReporting.ts
- src/modules/FeatureRequests.ts
- src/modules/Instabug.ts
- src/native.ts
- src/utils/ArgsRegistry.ts
- src/utils/Enums.ts
- test/mocks/mockInstabug.ts
- test/modules/BugReporting.spec.ts
- test/modules/FeatureRequests.spec.ts
- test/modules/Instabug.spec.ts
- test/utils/InstabugUtils.spec.ts
Introduce new standalone Enums that can be imported Directly from Instabug as follows:
```js
import Instabug, { InvocationEvent, LogLevel } from 'instabug-reactnative';
```
| Old (Deprecated)                  | New                       |
| --------------------------------- | ------------------------- |
| `Instabug.sdkDebugLogsLevel`      | `LogLevel`                |
| `Instabug.invocationEvent`        | `InvocationEvent`         |
| `Instabug.colorTheme`             | `ColorTheme`              |
| `Instabug.IBGPosition`            | `RecordingButtonPosition` |
| `Instabug.welcomeMessageMode`     | `WelcomeMessageMode`      |
| `Instabug.dismissType`            | `DismissType`             |
| `Instabug.extendedBugReportMode`  | `ExtendedBugReportMode `  |
| `Instabug.reproStepsMode` …
> [MOB-11550] Introduce New Enums

- ios/RNInstabug/InstabugBugReportingBridge.m
Changes the name of the native bug reporting `setDidSelectPromptOptionHandler` to match the one used on the JavaScript side.
> [MOB-11942] Fix Bug Reporting's Did Select Prompt Option Handler

- CHANGELOG.md
- RNInstabug.podspec
- android/build.gradle
- android/native.gradle
- ios/native.rb
Allow native apps that have recently integrated React Native within their apps to use Instabug native SDKs via the `instabug-reactnative` npm package as follows:
```gradle
apply from: "../../node_modules/instabug-reactnative/android/native.gradle"
```
```ruby
require_relative '../node_modules/instabug-reactnative/ios/native'
target 'CoolApp' do
use_instabug!
// ...
end
```
> [MOB-11946] Delegate Native SDKs

- CHANGELOG.md
- example/ios/Podfile.lock
- ios/native.rb
> [MOB-11948] Bump iOS SDK to `v11.9.0`

- package.json
- src/utils/IBGEventEmitter.ts
- test/mocks/mockParseErrorStackLib.ts
- test/setup.ts
- test/utils/InstabugUtils.spec.ts
- yarn.lock
Updates the SDK's React Native dev dependency version to 0.66 as an intermediate step for #924
> [MOB-11945] Update React Native Dev Dependency to 0.66

- CHANGELOG.md
- jest.config.js
- tsconfig.json
- tsconfig.test.json
**Problem**
A TS compile error started to arise on `v11.9.0` due to the `dist` dir having a different structure than the entry points provided in `package.json`. In particular, adding the `test` dir in `tsconfig.json` `include` property is the root cause of the change. This was done during the unit tests migration to TS to resolve an error related to the declaration file for module `xhr2`, which is inside the `test` dir. 
**Solution**
Remove the `test` dir from being included and add a separate `tsconfig.test.json` for the tests configuration, which would preserve the old `dist` structure and provide the required files for the tests to run. 
Note:
Changelog formatting according to the new guidelines will be done entirely in a separate PR.  
> [MOB-12026] Fix TS Compile Error

- CHANGELOG.md
- src/index.ts
- src/modules/NetworkLogger.ts
Re-exports `NetworkData` type to be imported from `instabug-reactnative`.
> [MOB-12027] Re-export `NetworkData` Type

- cli/UploadSourcemaps.ts
> [MOB-11997] Replace CLI `dir` flag with `file`

- .circleci/config.yml
- android/build.gradle
- example/.detoxrc.json
The upload scripts used to run while running both Unit and E2E CI jobs, resulting in more redundant time or unintended behavior. These scripts were disabled by:
1. **Android:** passing the `instabugUploadEnable` gradle property.
2. **iOS:** setting the `INSTABUG_SOURCEMAPS_UPLOAD_DISABLE` environment variable.
> [MOB-12070] Disable Sorucemaps Scripts on CI

- .circleci/config.yml
The checkout step used to take around a minute due to the size of the repo (1 GB). With shallow checkouts, it gets down to one second.
| Before | After |
| :---: |  :---: |
| ![before](https://user-images.githubusercontent.com/99807625/224938708-7b7a3a9f-33c3-4b62-987c-68051f438473.png) | ![after](https://user-images.githubusercontent.com/99807625/224940600-8df644a1-76e5-4f74-b575-d2d808cc6fac.png) |
> [MOB-12052] Use Shallow Checkout in CI

- .circleci/config.yml
Save around 4 minutes by caching pods.
| Before | After |
| :---: |  :---: |
| ![before](https://user-images.githubusercontent.com/99807625/225233426-02436323-7e6d-4dc8-a011-e8b01e1c9996.png) | ![after](https://user-images.githubusercontent.com/99807625/225233411-a7d5d393-4e20-4045-803b-3c70b1f5a966.png) |
> [MOB-12050] Cache CI Pods

- .circleci/config.yml
Why is this code there? I have no idea.
Was it needed in the past? Definitely.
Do we need it now? Not anymore.
> [MOB-12180] Remove Redundant CI Steps

- .circleci/config.yml
By using the `node` orb, we benefit from the following:
1. Default machine executors.
2. Caching `node_modules`.
| Before | After |
|:---:|:---:|
| ![before](https://user-images.githubusercontent.com/99807625/225598663-473c2d96-c680-4207-9fe5-235394dbdbd4.png) | ![after](https://user-images.githubusercontent.com/99807625/225603066-94ab0eb0-62be-41ea-b904-936ce9811795.png) |
> [MOB-12053] Use `node` CI Orb

- .circleci/config.yml
Migrate `e2e_ios` job's deprecated macOS large resource class machine to the new `macos.x86.medium.gen2`.
> [MOB-12204] Upgrade macOS Resource Class to Gen2

- .circleci/config.yml
- Fixes the issue addressed [here](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/).
> [MOB-12219] Bump `advanced-checkout` orb to `v1.1.0`

- .circleci/config.yml
- dangerfile.ts
- package.json
- yarn.lock
Integrates the repo with the new Danger code coverage plugin for visibility on code coverage on PRs.
> [MOB-11085] Integrate Danger Coverage Plugin

- CHANGELOG.md
- android/native.gradle
- Bump Android SDK to `v11.11.0`
> [MOB-12233] Bump Android SDK to `v11.11.0`

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
> [MOB-12241] Bump iOS SDK to `v11.10.1`

- CHANGELOG.md
- android/sourcemaps.gradle
The current sourcemaps upload script uses a Groovy method called endsWithIgnoreCase which is supported in Groovy 3 used by Gradle 7, while older versions of Gradle use older versions of Groovy (e.g. Gradle 6.9 uses Groovy 2.5.12) which don’t include this method. Hence, the build fails with the error:
```
FAILURE: Build failed with an exception.
* Where:
Script '[redacted]/node_modules/instabug-reactnative/android/sourcemaps.gradle' line: 8
* What went wrong:
No signature of method: java.lang.String.endsWithIgnoreCase() is applicable for argument types: (String) values: [bundleReleaseJsAndAssets]
```
We can replace the usage of endsWithIgnoreCase with another well-supported approach like .toLowerCase().endsWith (tested with React Native 0.66.1, Gradle 6.9, Groovy 2.5.12).
Fixes #969
> [MOB-12247] Fix Sourcemaps Script with Old Gradle

- CHANGELOG.md
- android/sourcemaps.gradle
The new Android sourcemaps upload script can’t detect the `[create]Bundle[Flavor]ReleaseJsAndAssets` when the user is using the Android product flavors feature.
Check for a suffix of `ReleaseJsAndAssets` instead of looking for a suffix of `bundleReleaseJsAndAssets` (ignoring the casing.)
Fixes #974
> [MOB-12305] Fix Sourcemaps Upload Script with Android Product Flavors

- CHANGELOG.md
- src/utils/InstabugUtils.ts
Fix an issue with unhandled JavaScript crashes not being reported correctly on Android when we removed the `setTimeout` around the original global error handler call.
> [INSD-9579] Fix Unhandled JavaScript Crashes on Android

- .circleci/config.yml
- CHANGELOG.md
- README.md
- android/sourcemaps.gradle
- examples/default/.detoxrc.json
- Deprecate `instabugUploadEnable` gradle property to disable Android Sourcemaps auto upload in favor of `INSTABUG_SOURCEMAPS_UPLOAD_DISABLE` env variable. 
> [MOB-12414] Disable Android Sourcemaps Upload with Env Var

- CHANGELOG.md
- android/native.gradle
- Bump Android SDK to `v11.12.0`
> [MOB-12434] Bump Android SDK to `v11.12.0`

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
> [MOB-12433] Bump iOS SDK to `v11.12.0`

- CHANGELOG.md
- android/sourcemaps.gradle
Fix an issue with the Android sourcemaps upload Gradle task getting recreated when both `bundleReleaseJsAndAssets` and `createBundleReleaseJsAndAssets` tasks exist in the same Android project by defaulting to the existent task when it exists.
Fixes #989
> [MOB-12473] Skip Recreating Sourcemaps Gradle Task If It Exists

- CHANGELOG.md
- android/jacoco.gradle
Replace the `enabled` method with `required` property in JaCoCo `gradle` plugin as it breaks the gradle scripts running on version `0.72`.
Fixes #994
> [MOB-12511] Replace JaCoCo’s `enabled` with `required`

- CHANGELOG.md
- android/native.gradle
> [MOB-12549] Bump Android SDK to v11.13.0

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
> [MOB-12550] Bump iOS SDK to v11.13.3

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java
- ios/RNInstabug/ArgsRegistry.m
- src/modules/Instabug.ts
- src/native/NativeConstants.ts
- src/utils/Enums.ts
- test/mocks/mockInstabug.ts
- test/modules/Instabug.spec.ts
- Deprecate `StringKey.reproStepsListItemTitle` as it has inconsistent behavior between Android and iOS (it puts an extra ` #` on iOS and doesn't put it on Android).
- Introduce a consistent `StringKey.reproStepsListItemNumberingTitle` which adds the ` #` on Android as well.
> [MOB-12640] Unify Repro Steps List Item Title String

- CHANGELOG.md
- android/build.gradle
- android/src/main/AndroidManifest.xml
Add SDK project `namespace` in `build.gradle` file to support the upcoming version of React Native(0.73) as it will use Android Gradle Plugin (AGP) version 8.x which will need the `namespace` to be specified. [More here](https://github.com/react-native-community/discussions-and-proposals/issues/671)
> [MOB-12515] Support React Native 0.73

- Gemfile
- Gemfile.lock
- Remove danger ruby package to resolve depenndabot git security vulnerability issue.
[MOB-12702](https://instabug.atlassian.net/browse/MOB-12702)
[MOB-12702]: https://instabug.atlassian.net/browse/MOB-12702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-12702] Remove danger ruby package

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
Removed the use of Java 8 lambda functions in Android that was added in #1012 and replaced it with `new Runnable` since it breaks apps running on older versions of Java and React Native.
Jira ID: MOB-12977
> refactor: use anonymous class instead of lambda

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump iOS SDK to 11.14.0
> [MOB-12991](https://instabug.atlassian.net/browse/MOB-12991) -- subtask of --> [MOB-12984](https://instabug.atlassian.net/browse/MOB-12984)
[MOB-12991]: https://instabug.atlassian.net/browse/MOB-12991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-12984]: https://instabug.atlassian.net/browse/MOB-12984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ios): bump sdk to 11.14.0

- CHANGELOG.md
- android/native.gradle
- test/modules/Instabug.spec.ts
Bump Android SDK to 11.14.0
> [MOB-12990](https://instabug.atlassian.net/browse/MOB-12990) -- subtask of --> [MOB-12984](https://instabug.atlassian.net/browse/MOB-12984)
[MOB-12990]: https://instabug.atlassian.net/browse/MOB-12990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-12984]: https://instabug.atlassian.net/browse/MOB-12984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(android): bump sdk to 11.14.0

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java
- ios/RNInstabug/ArgsRegistry.m
- src/utils/Enums.ts
Deprecate the old `StringKey.invalidCommentMessage` and `StringKey.invalidCommentTitle` in favor of `StringKey.insufficientContentMessage` and `StringKey.insufficientContentTitle`.
Jira ID: MOB-13020
> chore: deprecate old bug content string keys

- CHANGELOG.md
Fix typos in `CHANGELOG.md` file for 11.14.0
- Fix typo in inconsistency
- Fix wrong reference to the deprecated `reproStepsListItemTitle`
Jira ID: [MOB-13041](https://instabug.atlassian.net/browse/MOB-13041)
[MOB-13041]: https://instabug.atlassian.net/browse/MOB-13041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: resolve typos in changelog.md for 11.14.0

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump iOS SDK to v12.1.0
Jira ID: [MOB-13054](https://instabug.atlassian.net/browse/MOB-13054)
##Depends on
- #1027 
[MOB-13054]: https://instabug.atlassian.net/browse/MOB-13054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: bump ios sdk 12.1.0

- examples/default/metro.config.js
- examples/default/package.json
- examples/default/yarn.lock
Starting from React Native 0.72, Metro configs need to extend the default config to function correctly. In fact, Metro caching doesn’t function appropriately sometimes especially in release mode due to the config not extending the default config by Metro.
This also resolves the warning below that Metro shows whenever you run the app.
> warn From React Native 0.72, your metro.config.js file should extend'@react-native/metro-config'. Please see the React Native 0.72 changelog, or copy the template at:
https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn Falling back to internal defaults.
Jira ID: MOB-13156
> chore: extend default metro config

- jest.config.js
Whenever we run yarn test to run our JavaScript tests, we get this warning from Jest to update our Jest configuration format.
> ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config:migrate <config-file>.
> ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
> transform: {
>     <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
> },
> ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfig" is deprecated, use "[jest-config].globals.ts-jest.tsconfig" instead.
Updated the Jest config to follow the above logs instructions.
1. Putting `ts-jest`’s config in `transform` instead of `global`.
1. Using `tsconfig` instead of `tsConfig`.
Jira ID: MOB-13180
> chore: update outdated jest config format

- CHANGELOG.md
- android/build.gradle
- android/src/main/AndroidManifest.xml
The current implementation of Android Gradle Plugin >= 7.3.0 namespace support calculates `isManifestContentUpdated` before applying any modifications to the file, so the manifest file was never updated since `isManifestContentUpdated` will always be `false`. The fix was to calculate it right before writing the updates to the file.
I've changed the namespace support condition to check for AGP version >= 7.3 not only >= 7 since `namespace` support was added in v7.3.0. I've also refactored the code into functions and renamed some variables for readability.
I've also kept the `package` property in the initial `AndroidManifest.xml` file since having it removed by default causes the first app build to fail sometimes with apps not using AGP >= 7.3.0, while having it there in the initial run …
> fix: fix and enhance AGP namespace support

- CHANGELOG.md
- ios/RNInstabug/InstabugCrashReportingBridge.m
- src/modules/CrashReporting.ts
- src/native/NativeCrashReporting.ts
- src/utils/InstabugUtils.ts
Synchronize crash reporting fatal (unhandled) crashes with the iOS SDK through `Promise`s instead of assuming the JavaScript-native call is sync (and it's not).
Jira ID: MOB-13245
> chore(ios): sync JavaScript fatal crashes through promises

- CHANGELOG.md
- android/native.gradle
Bump Android sdk to `v12.1.0`
Jira ID: [MOB-13239](https://instabug.atlassian.net/browse/MOB-13239)
[MOB-13239]: https://instabug.atlassian.net/browse/MOB-13239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(android): bump sdk v12.2.0

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump iOS sdk to `v12.1.0`
Jira ID: [MOB-13240](https://instabug.atlassian.net/browse/MOB-13240)
[MOB-13240]: https://instabug.atlassian.net/browse/MOB-13240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ios): bump sdk v12.2.0

- CHANGELOG.md
- src/modules/Instabug.ts
Remove unnecessary mapping that mapped ReproStepsMode.enabled to ReproStepsMode.enabledWithNoScreenshots for iOS platform. This workaround was added due to an [issue](https://instabug.atlassian.net/browse/IBGCRASH-19924) with crashes repro steps with screenshots in the iOS SDK, and now it's no longer needed as the issue has been resolved. This re-enabled it for Crash Reporting and Session Replay.
Jira ID: [IBGCRASH-20555](https://instabug.atlassian.net/browse/IBGCRASH-20555)
[IBGCRASH-20555]: https://instabug.atlassian.net/browse/IBGCRASH-20555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ios): enable screenshots for crashes & sessions

- CHANGELOG.md
- examples/default/ios/InstabugExample.xcodeproj/project.pbxproj
- examples/default/ios/InstabugTests/InstabugSampleTests.m
- examples/default/ios/InstabugTests/RNInstabugTests.m
- ios/RNInstabug/InstabugReactBridge.m
- ios/RNInstabug/RNInstabug.h
- ios/RNInstabug/RNInstabug.m
- ios/RNInstabug/Util/Instabug+CP.h
Provide a native iOS-side `init` API that allows starting the SDK early (and before the JavaScript has started) in the app lifecycle allowing them to capture early crashes in their app.
1. Added `[RNInstabug initWithToken:invocationEvents:]` and `[RNInstabug initWithToken:invocationEvents:debugLogsLevel:]` APIs.
2. Refactored the native module method for `Instabug.init` to use `RNInstabug` internally.
Jira ID: MOB-13246
> feat(ios): add native-side init API for startup crashes

- .circleci/config.yml
`yarn build` working directory was set to package so it was looking for `project/project`
- [\[MOB-13252\] \[CP\] \[RN\] Fix NN automatic snapshot release ci - JIRA](https://instabug.atlassian.net/browse/MOB-13252)
[MOB-13252]: https://instabug.atlassian.net/browse/MOB-13252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: resolve nn ci issue

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
Get the Android `Application` instance when initializing the SDK through the `reactContext` instead of `getCurrentActivity` since it can be `null` sometimes causing the SDK to crash.
Jira ID: [\[INSD-10472\] \[Dream11\] Feature flag crashing IBG library ](https://instabug.atlassian.net/browse/INSD-10472)
> fix(android): get application through react context

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugCrashReportingModule.java
- src/utils/InstabugUtils.ts
Wait for Android SDK to process the crash by waiting for `sendJSCrashByReflection` to finish before we crash the app.
Jira ID: MOB-13312
- Test that an unhandled fatal crash is sent normally after relaunch
> chore(android): sync JS fatal crashes via promises

- CHANGELOG.md
- android/native.gradle
Bump Android SDK to `v12.4.1`
Jira ID: MOB-13346
> chore(android): bump sdk to v12.4.1

- examples/default/ios/Podfile.lock
- examples/default/package.json
- examples/default/patches/react-native+0.72.3.patch
- examples/default/yarn.lock
Patch the boost podspec source URL to fix the pod install checksum verification issue mentioned [here](https://github.com/boostorg/boost/issues/843#issuecomment-1872943124).
Jira ID: MOB-13588
> chore: fix react native boost install via patch

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump iOS SDK to `v12.5.0`
Jira ID: MOB-13556
> chore(ios): bump ios sdk 12.5.0

- CHANGELOG.md
- android/native.gradle
Bump Android SDK to `v12.5.1`
Jira ID: MOB-13556
> chore: bump android sdk 12.5.1

- android/src/main/java/com/instabug/reactlibrary/utils/ReportUtil.java
Update exception handling in parseConsoleLogs method to resolve the error related to JSON serialization exceptions. Modify the try-catch block to handle potential JSON exceptions effectively using a wider exceptions type.
Jira ID: MOB-13598
> fix(android): resolve `JsonException` handling error

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java
- src/modules/Instabug.ts
- src/native/NativeInstabug.ts
- test/mocks/mockInstabug.ts
- test/modules/Instabug.spec.ts
Utilize the new `reportCurrentView` API to report it immediately without delay. This eliminates the outdated 'Current View' values.
Jira ID: MOB-13396
> fix(android): remove current view update delay

- examples/default/android/app/src/main/res/xml/network_security_config.xml
Add Instabug API domains to network security config, in order to allow remote mapping for testing purposes.
Jira ID: MOB-13665
> chore(android): add Instabug API domains to network security config

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump iOS SDK to `v12.6.0`
Jira ID: MOB-13670
> chore(ios): bump sdk to v12.6.0

- CHANGELOG.md
- android/native.gradle
Bump Android SDK to `v12.6.0`
Jira ID: MOB-13669
> chore(android): bump sdk to v12.6.0

- scripts/dream-11-delete-unused-features.sh
1. fix the dream11 manifest error by disabling codenames
Jira ID: INSD-10749
> fix: dream11 manifest issue

- .circleci/config.yml
> fix: dream11 package name in CI

- .gitignore
- examples/default/src/components/InputField.tsx
- examples/default/src/components/NestedView.tsx
- examples/default/src/navigation/HomeStack.tsx
- examples/default/src/screens/user-steps/BasicComponentsScreen.tsx
- examples/default/src/screens/user-steps/ComplexViewsScreen.tsx
- examples/default/src/screens/user-steps/UserStepsScreen.tsx
Allows testing using complex nested views
Jira ID: MOB-13737
> feat(example): add nested complex views

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
1. Fix set codepush version in hybrid apps by
1. if SDK is initialized before then use setCodePushVersion
2. if SDK hasn't  initialized yet then set Codepush version using Builderbuilder.setCodePushVersion
Jira ID:  [MOB-13727](https://instabug.atlassian.net/browse/MOB-13727)
[MOB-13727]: https://instabug.atlassian.net/browse/MOB-13727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Android):  codepush version init in hybrid mode 

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java
- examples/default/ios/InstabugTests/InstabugSampleTests.m
- ios/RNInstabug/InstabugReactBridge.h
- ios/RNInstabug/InstabugReactBridge.m
- src/modules/Instabug.ts
- src/native/NativeInstabug.ts
- test/mocks/mockInstabug.ts
- test/modules/Instabug.spec.ts
Support the new API which allows identifying user with ID.
Jira ID: MOB-13746
> feat: support identify user by id

- .circleci/config.yml
> ci: replace  d11 cluster url in UploadSourcemaps

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
Eliminate the use of `UIManagerModule.prependUIBlock` which causes crashes due to `UIOperation` objects being `null` while React Native's `UIViewOperationQueue` is trying to execute it which causes a `NullPointerException`, and instead resolve the view directly using `UIManagerModule.resolveView`.
Jira ID: INSD-10851
Fixes #514
> fix(android): resolve private views through UI manager directly

- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- examples/default/ios/InstabugTests/InstabugSampleTests.m
- examples/default/ios/InstabugTests/RNInstabugTests.m
- ios/RNInstabug/InstabugReactBridge.h
- ios/RNInstabug/InstabugReactBridge.m
- ios/RNInstabug/RNInstabug.h
- ios/RNInstabug/RNInstabug.m
- src/models/InstabugConfig.ts
- src/modules/Instabug.ts
- src/native/NativeInstabug.ts
- src/utils/Enums.ts
- test/mocks/mockNetworkLogger.ts
- test/modules/Instabug.spec.ts
Add a new `Instabug.init` config property (`networkInterceptionMode`) which allows switching between JavaScript and native network interception through JavaScript.
When the network interception mode is JavaScript, the SDK functions as it used to:
1. Network interception is done through JavaScript.
2. You can set an obfuscation handler and request filtering in the JavaScript code.
3. Network requests sent through native code don't get captured.
Native network interception provides the following:
1. Network interception is done through the native SDKs (the native iOS SDK works out of the box and the Android SDK requires configuring the [Instabug APM network plugin](https://docs.instabug.com/docs/android-apm-network#getting-started).
2. You can't set an obfuscation handler and request …
> feat: support switching to native network interception

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump iOS SDK to `v12.7.0`
Jira ID: MOB-13965
> chore(ios): bump sdk to v12.7.0

- CHANGELOG.md
- android/native.gradle
Bump Android SDK to `v12.7.0`
Jira ID: MOB-13964
> chore(android): bump sdk to v12.7.0

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- android/src/main/java/com/instabug/reactlibrary/utils/RNTouchedViewExtractor.java
- examples/default/src/App.tsx
- examples/default/src/screens/user-steps/BasicComponentsScreen.tsx
Support Capturing the label of buttons for repro-steps via adding custom implementation for the Touched View Extractor.
Jira ID: 
- IBGCRASH-21078
- IBGCRASH-21213
> feat: support react native buttons label extraction in user steps

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugCrashReportingModule.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugCrashReportingModuleTest.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugRepliesModuleTest.java
- examples/default/android/app/src/main/java/com/instabug/react/example/MainApplication.java
- examples/default/android/app/src/main/java/com/instabug/react/example/RNInstabugExampleCrashReportingModule.java
- examples/default/android/app/src/main/java/com/instabug/react/example/RNInstabugExampleReactnativePackage.java
- examples/default/ios/InstabugExample.xcodeproj/project.pbxproj
- examples/default/ios/native/CrashReportingExampleModule.h
- examples/default/ios/native/CrashReportingExampleModule.m
- examples/default/src/components/PlatformListTile.tsx
- examples/default/src/native/NativeCrashReporting.ts
- examples/default/src/native/NativePackage.ts
- examples/default/src/screens/CrashReportingScreen.tsx
- src/modules/CrashReporting.ts
- src/native/NativeCrashReporting.ts
- test/mocks/mockCrashReporting.ts
- test/modules/CrashReporting.spec.ts
1) Map setNDKCrashesEnabled in Javascript side
Jira ID:MOB-13774
[MOB-13774]: https://instabug.atlassian.net/browse/MOB-13774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add setNDKCrashesEnabled API

- examples/default/android/app/src/main/AndroidManifest.xml
- examples/default/android/app/src/main/res/values/strings.xml
- examples/default/ios/InstabugExample/AppDelegate.mm
- examples/default/ios/Podfile
- examples/default/package.json
- examples/default/src/navigation/HomeStack.tsx
- examples/default/src/screens/user-steps/GoogleMapsScreen.tsx
- examples/default/src/screens/user-steps/UserStepsScreen.tsx
- examples/default/yarn.lock
1. add Google maps screen
Jira ID = MOB-13923
> feat(example): add google maps screen

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java
- examples/default/ios/InstabugTests/InstabugSampleTests.m
- ios/RNInstabug/InstabugReactBridge.h
- ios/RNInstabug/InstabugReactBridge.m
- src/modules/Instabug.ts
- src/native/NativeInstabug.ts
- test/mocks/mockInstabug.ts
- test/modules/Instabug.spec.ts
Add `Instabug.setCodePushVersion` API to set the code push version at runtime rather than when calling `Instabug.init`.
Jira ID: MOB-14029
> feat: add runtime code push version API

- CHANGELOG.md
- android/native.gradle
Bump Android SDK to `v12.8.0`
Jira ID: MOB-14054
> chore(android): bump sdk to v12.8.0

- .circleci/config.yml
> upgrade android orb from 2.0 to 2.5.0 (latest).
upgrade node orbe from 5.1.0 to 5.2.0 (latest).
upgrade the deprecated android image 2022.04.1 to default
> JiraID: MOB-14218
> ci: upgrade android orb, node orb and android image 

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
bump iOS SDK to v13.0.0
JIRA ID : MOB-14362
> chore(ios): bump SDK to v13.0.0

- .circleci/config.yml
- .eslintrc.js
- scripts/replace.js
1. Change the find and replace logic in CI code to use a JavaScript script instead of `sed` to avoid issues with escaping special characters.
2. Refactor NN and Injazat's release to use the same job but with different parameters instead of different jobs.
3. Fix NN, Injazat, and Dream11's packages sourcemaps upload script, the `ios/sourcemaps.sh` and `android/sourcemaps.gradle` scripts referred to `instabug-reactnative` to invoke the upload CLI in the past so we fixed the release pipelines to replace all occurrences of `instabug-reactnative` with the new package name in these files as well.
4. Replace the API URL used to upload SO files in the CLI to refer to the API URL of the customer instead of the default Instabug API.
I tested the new `release_custom_package` and `release_d11` CI …
> ci: fix and refactor enterprise release pipeline

- CHANGELOG.md
The diff link for `v13.0.0` and `v12.9.0` were referring to `v12.9.0...dev` and `v12.8.0...dev` while they should refer to `v12.9.0...v13.0.0` and `v12.8.0...v12.9.0` in the Changelog.
Jira ID: MOB-14388
> fix: use correct diff link for v13.0.0, v12.9.0 releases

- .circleci/config.yml
1. remove the  last colon from the d11 package name
2. 
JIRA ID : MOB-14387
> CI: fix d11 pipeline

- .circleci/config.yml
Lock the Android machine to tag `2024.01.1` to resolve CI failures in `test_android` and `e2e_android`.
Jira ID: MOB-14564
> ci: lock android machine to tag 2024.01.1

- .circleci/config.yml
Restrict running `release_nn` and `release_injazat` to `master`, and `release_d11` to `dream11`
Jira ID: MOB-14565
> ci: restrict enterprise release jobs branches

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump Instabug iOS SDK to `v13.0.3`
Jira ID: MOB-14567
> chore(ios): bump sdk to v13.0.3

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump iOS SDK to `v13.0.5`.
Jira ID: MOB-14591
> chore(ios): bump sdk to v13.0.5

- CHANGELOG.md
- android/build.gradle
- examples/default/ios/Podfile.lock
- ios/native.rb
- package.json
Sync `dream11` branch with `master` for release.
Jira ID: MOB-14593
> chore: sync `dream11` with `master`

- examples/default/ios/Podfile.lock
Sync `Podfile.lock` to fix the failing `sync_generated_files` CI job.
Jira ID: MOB-14767
> chore: sync podfile lock

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugCrashReportingModule.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugSessionReplayModule.java
Mark the parameters used inside inner classes in the Android code as `final` to fix errors like the one below in Java 7 and earlier.
> Error: local variable version is accessed from within inner class; needs to be declared final in RNInstabugReactnativeModule.java
Jira ID: INSD-11725
> fix(android): change parameters used in inner class to final

- CHANGELOG.md
- android/native.gradle
Bump Instabug Android SDK to v13.2.0
Jira ID: MOB-14896
> chore(android): bump sdk to v13.2.0

- CHANGELOG.md
- android/native.gradle
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump Instabug iOS SDK to v13.2.0
Jira ID: MOB-14897
> chore(ios): bump sdk to v13.2.0

- CHANGELOG.md
Resolve issues in the Changelog in the 2 previous releases.
1. Remove duplicate Changed section in the 13.2.0 release due to a merge conflict.
2. Make 13.1.1's release notes compliant with our Changelog guidelines.
Jira ID: MOB-14901
> chore: resolve issues in changelog

- CHANGELOG.md
- examples/default/ios/Podfile
- examples/default/ios/Podfile.lock
- examples/default/package.json
- examples/default/src/App.tsx
- examples/default/src/components/ClipboardTextInput.tsx
- examples/default/src/components/CustomButton.tsx
- examples/default/src/components/CustomImage.tsx
- examples/default/src/components/CustomText.tsx
- examples/default/src/components/InputField.tsx
- examples/default/src/components/PasteFromClipboardButton.tsx
- examples/default/src/navigation/HomeStack.tsx
- examples/default/src/screens/HomeScreen.tsx
- examples/default/src/screens/apm/APMScreen.tsx
- examples/default/src/screens/apm/FlowsScreen.tsx
- examples/default/src/screens/apm/NetworkScreen.tsx
- examples/default/src/screens/apm/TracesScreen.tsx
- examples/default/yarn.lock
Support the following Screens:
| APM  | Network traces | Execution traces | App flows |
|-----------|-----------|-----------|-----------|
| ![APM_Screen](https://github.com/Instabug/Instabug-React-Native/assets/38096011/342e1534-004e-47e7-bbcf-f24a0a491cf5) | ![Network_Traces_Screen](https://github.com/Instabug/Instabug-React-Native/assets/38096011/d08681bb-d0d6-48c6-8ea3-6fbca77b4702) | ![Execution_Traces_Screen](https://github.com/Instabug/Instabug-React-Native/assets/38096011/e65a6a9f-9242-49d7-a84c-7837991b225e) | ![App_Flows_Screen](https://github.com/Instabug/Instabug-React-Native/assets/38096011/fc22cd64-6035-49b4-8e60-289541d38bfd) |
Jira ID: APM-19537
> feat(example): add apm screen

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabugAPMModule.java
Add W3C External Trace Attributes Placeholder For Android 
Jira ID: MOB-14970
> fix(android): add W3C external trace attributes placeholder

- android/src/main/java/com/instabug/reactlibrary/RNInstabugAPMModule.java
change network timestamp in android side from milliSeconds into microSeconds
JIRA ID : MOB-15317
> fix(android): pass network start time in microseconds

- CHANGELOG.md
- android/native.gradle
Bump Instabug Android SDK to v13.3.0
Jira ID: MOB-15319
> chore(android): bump sdk to v13.3.0

- CHANGELOG.md
- android/native.gradle
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump Instabug iOS SDK to v13.3.0
Jira ID: MOB-15321
> chore(ios): bump sdk to v13.3.0

- CHANGELOG.md
The App Flows changelog items have been duplicated due to merging the APM screens #1141 besides the deprecation of the Execution Traces entry being added under `v12.9.0` instead of `v13.0.0`.
This PR fixes these issues in the Changelog.
Jira ID: MOB-15323
> chore: remove duplicate app flows changelog entries

- CHANGELOG.md
There's still a duplicate execution traces deprecation entry under `v12.8.0`, this PR removes it.
Jira ID: MOB-15323
> chore: remove duplicate execution traces deprecation in changelog

- examples/default/src/App.tsx
- src/modules/Instabug.ts
- test/modules/Instabug.spec.ts
Support navigation tracking with expo router 
[ID:MOB-15377](https://instabug.atlassian.net/browse/MOB-15377)
> feat: navigation tracking support with expo router

- android/native.gradle
- android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java
- android/src/main/java/com/instabug/reactlibrary/Constants.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugSessionReplayModule.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugSessionReplayModuleTest.java
- examples/default/e2e/reportBug.e2e.ts
- examples/default/src/App.tsx
- src/index.ts
- src/models/SessionMetadata.ts
- src/modules/SessionReplay.ts
- src/native/NativeConstants.ts
- src/native/NativeSessionReplay.ts
- src/utils/Enums.ts
- test/mocks/mockSessionReplay.ts
- test/modules/SessionReplay.spec.ts
Add a callback for session replay to determine weather to sync the session
[jiraID:MOB-15002](https://instabug.atlassian.net/browse/MOB-15002)
> feat(android): add session sync callback

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
Bump Instabug iOS SDK to v13.4.1
Jira ID: MOB-15855
> chore(ios): bump sdk to v13.4.1

- android/sourcemaps.gradle
Resolve the correct app version name and version code to use when uploading the source map file to the dashboard on Android when using different versions for different variants/flavors (e.g. flavors that set a suffix to the version name).
Jira ID: INSD-11595
> fix(android): resolve correct app version with flavors in source map upload

- CHANGELOG.md
- examples/default/ios/InstabugTests/InstabugCrashReportingTests.m
- ios/RNInstabug/InstabugCrashReportingBridge.m
The API for reporting JavaScript crashes on iOS has been changed from `Instabug.reportCrashWithStackTrace` to `CrashReporting.cp_reportFatalCrashWithStackTrace` in the native iOS SDK as part of v13.1.0 but the React Native SDK wasn't updated to use the new API. This led to fatal JavaScript crashes being reported by the iOS SDK as native crashes rather than JavaScript crashes breaking symbolication for these crashes.
This PR updates the API to be the new one to fix this bug.
Jira ID: MOB-16163
> fix(ios): report fatal crashes with the updated api

- CHANGELOG.md
- android/build.gradle
- android/native.gradle
- examples/default/ios/InstabugTests/InstabugSampleTests.m
- examples/default/ios/Podfile.lock
- ios/RNInstabug/InstabugReactBridge.m
- ios/RNInstabug/Util/IBGNetworkLogger+CP.h
- ios/native.rb
- package.json
Release v13.4.0.
Jira ID: MOB-15855
> release: v13.4.0

- android/native.gradle
- examples/hybrid/App.tsx
- examples/hybrid/android/app/build.gradle
- examples/hybrid/android/app/src/main/java/com/instabug/hybridsampleapp/HybridApplication.java
- examples/hybrid/android/app/src/main/java/com/instabug/hybridsampleapp/MainActivity.java
- examples/hybrid/android/app/src/main/res/layout/activity_main.xml
- examples/hybrid/android/app/src/main/res/values/strings.xml
- examples/hybrid/android/settings.gradle
- examples/hybrid/ios/HybridSampleApp.xcodeproj/project.pbxproj
- examples/hybrid/ios/HybridSampleApp/AppDelegate.m
- examples/hybrid/ios/HybridSampleApp/Base.lproj/Main.storyboard
- examples/hybrid/ios/HybridSampleApp/MainViewController.h
- examples/hybrid/ios/HybridSampleApp/MainViewController.m
- examples/hybrid/ios/Podfile
- examples/hybrid/ios/Podfile.lock
- examples/hybrid/package.json
- examples/hybrid/yarn.lock
> Customize the hybrid App with Dream11 Customization 
1- integrating with codepush
2- customizing networking for android and ios for more details [check DOCS](https://instabug.atlassian.net/wiki/spaces/CP/pages/4574838874/Dream11+Hybrid+Setup)
> [Issue links go here](https://instabug.atlassian.net/browse/MOB-16272)
> feat: customizing app with dream11 configuration

- examples/utils/proxy-server.py
> change mitm proxy to use env variables (Domain,Token) to be dynamically used
> [Issue links go here](https://instabug.atlassian.net/browse/MOB-16695)
> feat: refactor mitm proxy script

- examples/default/src/screens/BugReportingScreen.tsx
Adding Buttons to the sample app
RL-231
> feat(example): add buttons to sample app 

- CHANGELOG.md
- android/build.gradle
- android/native.gradle
- examples/default/ios/Podfile.lock
- ios/native.rb
- package.json
Release: 14.1.0
JIRA ID : MOB-17068
> Release:14.1.0

- examples/default/src/components/CustomGap.tsx
- examples/default/src/screens/apm/APMScreen.tsx
Add ComplexViews to APM screen
Jira ID: APM-21684
> chore: add ComplexViews to APM screen

- scripts/dream-11-delete-unused-features.sh
release(dream11):14.0.3-fix
JIRA ID :
> release(dream11):14.0.3-fix

- CHANGELOG.md
- examples/default/ios/Podfile.lock
- ios/native.rb
> Bump Instabug iOS SDK to v14.3.0
> chore(ios): bump sdk to v14.3.0

- RNInstabug.podspec
- examples/default/ios/Podfile
- examples/default/ios/Podfile.lock
> use iOS sanity podspec that supports network spans
> chore: use iOS sanity podspec

- CHANGELOG.md
- RNInstabug.podspec
- android/build.gradle
- android/native.gradle
- android/src/main/java/com/instabug/reactlibrary/RNInstabugAPMModule.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- examples/default/ios/InstabugTests/InstabugSampleTests.m
- examples/default/ios/Podfile.lock
- examples/default/package.json
- examples/default/src/components/CustomGap.tsx
- examples/default/src/screens/apm/APMScreen.tsx
- examples/default/yarn.lock
- ios/RNInstabug/InstabugAPMBridge.m
- ios/RNInstabug/InstabugCrashReportingBridge.m
- ios/RNInstabug/InstabugReactBridge.h
- ios/RNInstabug/InstabugReactBridge.m
- ios/native.rb
- package.json
- src/modules/APM.ts
- src/modules/NetworkLogger.ts
- src/native/NativeInstabug.ts
- test/mocks/mockInstabug.ts
- test/modules/NetworkLogger.spec.ts
> chore: Release 14.3.0

- android/native.gradle
- android/src/main/java/com/instabug/apm/networking/ApmNetworkLoggerHelper.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugAPMModule.java
Replace APM API that uses reflection by a package private API
Jira ID: APM-22030
> refactor: Replace APM API that uses reflection by a package private API

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugBugReportingModule.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugBugReportingModuleTest.java
- examples/default/ios/InstabugTests/InstabugBugReportingTests.m
- ios/RNInstabug/ArgsRegistry.h
- ios/RNInstabug/ArgsRegistry.m
- ios/RNInstabug/InstabugBugReportingBridge.h
- ios/RNInstabug/InstabugBugReportingBridge.m
- ios/RNInstabug/RCTConvert+InstabugEnums.m
- src/modules/BugReporting.ts
- src/native/NativeBugReporting.ts
- src/native/NativeConstants.ts
- src/utils/Enums.ts
- test/mocks/mockBugReporting.ts
> support bug reporting user consents
> [Issue links go here](https://instabug.atlassian.net/browse/MOB-18096)
> feat: support bug reporting user consents

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabug.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugTest.java
- examples/default/ios/InstabugTests/InstabugSampleTests.m
- ios/RNInstabug/InstabugReactBridge.h
- ios/RNInstabug/InstabugReactBridge.m
- src/models/InstabugConfig.ts
- src/modules/Instabug.ts
- src/native/NativeInstabug.ts
- test/modules/Instabug.spec.ts
a flag to override SDK screenshot security behavior on Android devices
JIRA ID : MOB-19399
> feat: support ignore flag secure on android.

- CHANGELOG.md
- android/src/main/java/com/instabug/reactlibrary/RNInstabug.java
- android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- android/src/test/java/com/instabug/reactlibrary/RNInstabugTest.java
- examples/default/ios/InstabugTests/InstabugSampleTests.m
- examples/default/src/App.tsx
- ios/RNInstabug/InstabugNetworkLoggerBridge.h
- ios/RNInstabug/InstabugNetworkLoggerBridge.m
- ios/RNInstabug/InstabugReactBridge.h
- ios/RNInstabug/InstabugReactBridge.m
- src/models/InstabugConfig.ts
- src/modules/Instabug.ts
- src/native/NativeInstabug.ts
- src/native/NativeNetworkLogger.ts
- test/modules/Instabug.spec.ts
- test/utils/InstabugUtils.spec.ts
> Release: v15.0.2

- .circleci/config.yml
ci: fix custom release package
JIRA ID :
> ci: fix custom release package
