android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
- Refactoring use of strings in internal functions to use constatns
- Expose string constants through `getConstants` react method.
@DevHossamHassan trying to address this issue https://github.com/Instabug/instabug-reactnative/issues/6
=> Implementing constants bridge for andriod

android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
fix for issue https://github.com/Instabug/instabug-reactnative/issues/29
=> Fix setUserName typo

android/build.gradle
Updated versions of gradle require 25.X.X
=> Update build tools version

ios/RNInstabug/InstabugReactBridge.m
@Kmohamed @yousefhamza Can you please review this PR?
=> 🐛 Fix a bug where the app crashes on iOS 8 due to os_logs.

android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
=> Fixes setString method name for android

ios/Instabug.framework/InstabugResources.bundle/Instabug_dsym_upload.sh
Added missing os=ios param
Fixes https://github.com/Instabug/Instabug-React-Native/issues/239
=> Fixed curl command in Instabug_dsym_upload.sh

index.d.ts
Aligned **hasChats** signature type definition to its behaviour https://github.com/Instabug/Instabug-React-Native/releases/tag/v8.1.5
=> changed hasChats signature

android/upload_sourcemap.sh, package.json
Fix wrong params in curl request for android sourcemap script
=> 💎Bump version to 8.2.5

index.js, package.json
=> Hotfix 8.3.1

CHANGELOG.md, index.d.ts, index.js, ios/RNInstabug/InstabugReactBridge.m, ios/RNInstabug/RCTConvert+InstabugEnums.m, package.json
remove the `enabled` enum from reproSteps
=> 📝 removing reproStepsMode enabled enum

.circleci/config.yml, Dangerfile
Adds Danger config for PR description and changelog entry
=> ✨ Adds danger config

CHANGELOG.md, android/build.gradle, ios/RNInstabug/InstabugReactBridge.m, package.json
* Fixes onReportSubmitHandler freezing
* Fixes build error in release mode on android
=> onReportSubmitHandler Fix + Windows Android release fix

.circleci/config.yml, android/build.gradle, android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java
* Adds native android tests skeleton 
* Adds circleci config to run native android tests
=> ✨ Adds native android tests

CHANGELOG.md, InstabugSample/android/build.gradle, InstabugSample/android/gradle/wrapper/gradle-wrapper.properties, android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java
* Adds android unit tests for the following modules:
* Crash Reporting
* Surveys
* Chats
* Replies
* Feature Requests
=> 📝 Adds crash reporting & surveys testing

InstabugSample/ios/InstabugSampleTests/InstabugSampleTests.m, ios/RNInstabug/InstabugReactBridge.h
* Adds Native tests for BugReporting Module
=> [iOS native tests] - BugReporting Module 

InstabugSample/ios/InstabugSampleTests/InstabugSampleTests.m, ios/RNInstabug/InstabugReactBridge.h, ios/RNInstabug/InstabugReactBridge.m
* Adds Native iOS tests for feature requests and replies module
=> [iOS Native Tests] - Feature Requests & Replies Modules

InstabugSample/ios/InstabugSampleTests/InstabugSampleTests.m, ios/RNInstabug/InstabugReactBridge.h
=> ✨ Surveys iOS tests

README.md
=> 🔥 Remove CI badge

CHANGELOG.md, ios/RNInstabug/InstabugReactBridge.m
* Replace perform block with perform selector
=> Perform block fix

CHANGELOG.md, android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java
* Used method `PowerMockito.verifyPrivate` to verify calls by reflection
=> 📝 handle unit testing with reflection

CHANGELOG.md, android/src/main/java/com/instabug/reactlibrary/RNInstabugBugReportingModule.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugChatsModule.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugFeatureRequestsModule.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugRepliesModule.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugSurveysModule.java, android/src/main/java/com/instabug/reactlibrary/utils/InstabugUtil.java, android/src/main/java/com/instabug/reactlibrary/utils/MainThreadHandler.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugBugReportingModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugChatsModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugFeatureRequestsModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugRepliesModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugSurveysModuleTest.java
* Run all Instabug Android method calls on main thread
=> Run all Instabug Android method calls on main thread

CHANGELOG.md, InstabugSample/android/app/src/main/java/com/instabugsample/MainApplication.java, README.md, __tests__/index.spec.js, android/build.gradle, index.js, package.json
* remove android initialization from JS side
* updates changelog
* updates readme
=> Revert android initialization from JS

index.d.ts
Changed methods signature:
- getUnreadRepliesCount
- getUnreadMessagesCount
=> Changed getUnreadRepliesCount signature

android/build.gradle
=> Enable multidex on Android

android/build.gradle, android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java
Add defensive code for hideView API.
=> Add defensive code for hideView API [INSD-3722]

InstabugSample/ios/InstabugSampleTests/InstabugSampleTests.m, __tests__/index.spec.js, index.d.ts, index.js, ios/RNInstabug/InstabugReactBridge.h, ios/RNInstabug/InstabugReactBridge.m, ios/RNInstabug/RCTConvert+InstabugEnums.m, jest/mockInstabug.js
✨ Added new enum sdkDebugLogsLevel
✨ Added mapping for Instabug.setSdkDebugLogsLevel iOS API
✅ Added iOS specs
✅ Added JS specs
=> Mapping for `Instabug.setSdkDebugLogsLevel` [MOB-4367]

CHANGELOG.md, index.d.ts, package.json
=> Release 9.1.7

index.d.ts
Add missing param for `surveyTokenCallback`
=> [INSD-4385] Add missing param in TS spec

.circleci/config.yml, package.json
* Fixes an issue causing the CI to fail due to Yarn
=> Fixing Yarn issue in CI

CHANGELOG.md, ios/upload_sourcemap.sh
* Adds source map upload script support for environment variables use inside info.plist
https://instabugteam.slack.com/archives/GHK5TA7AR/p1599122041127500?thread_ts=1599122041.127500&cid=GHK5TA7AR
=> Update Source map upload script

ios/RNInstabug/InstabugReactBridge.m
* Adds defensive code when the user attribute does not exist
https://instabugteam.slack.com/archives/GHK5TA7AR/p1604505379332200
=> Add defensive code for getUserAttribute

CHANGELOG.md, package.json
=> Release 9.1.10

__tests__/index.spec.js, __tests__/replies.spec.js, android/src/main/java/com/instabug/reactlibrary/RNInstabugRepliesModule.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugRepliesModuleTest.java, index.d.ts, jest/mockReplies.js, modules/Replies.js
- Support of Push Notifications
=> Feature/Push Notifications

index.d.ts, index.js, modules/APM.js, modules/CrashReporting.js, typescript_validator.js
- Fixes discrepancies reported by the type validator, hence, resolves CircleCI errors.
=> Fix discrepancies reported by the type validator

__tests__/xhrNetworkInterceptor.spec.js, utils/XhrNetworkInterceptor.js
- Fixed network logger crash on dev.
- Adjusted unit test accordingly.
=> Fix network logger crash on dev

.circleci/config.yml
Fixed a configuration issue. Details inside the ticket.
=> [MOB-4988] Update CI publish script

CHANGELOG.md, __tests__/replies.spec.js, android/src/main/java/com/instabug/reactlibrary/RNInstabugRepliesModule.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugRepliesModuleTest.java, index.d.ts, jest/mockReplies.js, modules/Replies.js
Added new API: Replies.showNotificationAndroid
=> [MOB-5157] Add new API: Replies.showNotificationAndroid

android/upload_sourcemap.sh
- Fixed Hermes sourcemap generation for a successful upload process
=> [MOB-5167] Fix/android sourcemap upload

InstabugSample/yarn.lock, yarn.lock
Updated dependencies reported by dependabot.
=> [MOB-5214] Update package dependencies

.circleci/config.yml
- Updates CI release hold required jobs.
=> [MOB-5605] Update config.yml

ios/upload_sourcemap.sh
> change command read for file info.plist
=> [MOB-5929] - Fix upload source map ios

RNInstabug.podspec, link.rb, link_bridge.js, unlink.rb, unlink_bridge.js
- Refactor package name references
=> [MOB-5991] Refactor package name references

.circleci/config.yml
=> [MOB-6319] Pause android tests suite (temporarily)

.circleci/config.yml, Dangerfile, InstabugSample/metro.config.js, android/build.gradle, android/src/test/java/com/instabug/reactlibrary/RNInstabugAPMModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugBugReportingModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugChatsModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugFeatureRequestsModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugRepliesModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugSurveysModuleTest.java
-  Replaced Powermock with Mockito
-  Changed all tests accordingly
=> [MOB-6479] Fix Failing Android Tests

InstabugSample/App.js, InstabugSample/android/app/src/main/java/com/instabugsample/MainApplication.java
=> [MOB-7961] Update Sample App token

README.md
=> [MOB-7959] Minimize README Sections

CHANGELOG.md, utils/InstabugConstants.js
Change graphql header to kebab case, as header keys are lower-cased by default in http requests
=> [MOB-7958] Change graphql request header

README.md
Updates the integration docs for Android.
=> [MOB-7917] Update Integration Steps for Android

README.md
- Removed broken URL
- Removed unnecessary header
=> [MOB-8880] Update README Format

.circleci/config.yml, package.json
- Bump codecov
- Bump CI node (codecov dependency)
=> [MOB-8892] Update codecov version

.circleci/config.yml
=> [MOB-8894] Increase CI emulator memory

android/src/test/java/com/instabug/reactlibrary/RNInstabugBugReportingModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugSurveysModuleTest.java
Fixed failing event tests in Bug Reporting and Surveys.
=> [MOB-8935] Fix failing event tests

yarn.lock
This file got out of sync after bumping `react-native` in #748 
=> [MOB-9968] Sync root `yarn.lock`

.github/dependabot.yml
Update dependabot interval and ignored versions
=> [MOB-9350] Update Dependabot Config

package.json, yarn.lock
- #698 
- #712 
- #716 
- #759 
- #765 
- #766
- #767
=> [MOB-9976] Bump Dependencies

InstabugSample/package.json, InstabugSample/yarn.lock, package.json, yarn.lock
Runs `yarn upgrade` in both root and example folders.
=> [MOB-10004] Bump All Dependencies

RNInstabug.podspec, android/build.gradle, package.json
=> [MOB-10035] Update Package Metadata

CHANGELOG.md, android/build.gradle, package.json
=> [MOB-10040] Bump version to 11.2.0

codecov.yml, package.json
=> [MOB-10140] Collect Coverage Reports From All Source Files

.circleci/config.yml, package.json, yarn.lock
=> [MOB-10139] Migrate to Codecov's New Uploader CircleCI Orb

package.json, src/modules/Instabug.js, tests/modules/BugReporting.spec.js, tests/modules/Instabug.spec.js, tests/utils/InstabugUtils.spec.js, typescript_validator.js
=> [MOB-10384] Move `index.js` to `modules/Instabug.js`

package.json, src/index.js, src/modules/Instabug.js
=> [MOB-10385] Create Barrel Entry File

.circleci/config.yml, CHANGELOG.md, android/build.gradle, package.json
=> [MOB-10376] Release `v11.3.0`

.circleci/config.yml, android/build.gradle, android/jacoco.gradle, codecov.yml
Collect coverage from our Android code using JaCoCo and upload it to Codecov.
=> [MOB-10129] Collect Coverage Reports from Android

.circleci/config.yml, codecov.yml, example/ios/InstabugSample.xcodeproj/xcshareddata/xcschemes/InstabugSample.xcscheme
=> [MOB-10136] Collect Coverage Reports from iOS

package.json, yarn.lock
- #811
- #816 
- #817
- #819
- #820
=> [MOB-10538] Bump Dependencies

example/android/build.gradle
React Native apps [fail to build on Android](https://github.com/facebook/react-native/issues/35210), this fixes our example app Android build.
=> [MOB-10557] Fix Example App Android Build

CHANGELOG.md, android/build.gradle
=> [MOB-10849] Bump Android SDK to `v11.6.0`

CHANGELOG.md, RNInstabug.podspec
=> [MOB-10850] Bump iOS SDK to `v11.5.0`

CHANGELOG.md, android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java, ios/RNInstabug/ArgsRegistry.m, src/utils/ArgsRegistry.ts
=> [INSD-7895] Add Romanian Locale

CHANGELOG.md, android/build.gradle, package.json
=> [MOB-10886] Release 11.5.0

CHANGELOG.md, android/build.gradle, package.json
=> [MOB-10997] Release v`11.5.1`

CHANGELOG.md, android/build.gradle
=> [MOB-11426] Bump Android SDK to `v11.7.0`

CHANGELOG.md, RNInstabug.podspec
[MOB-11426]: https://instabug.atlassian.net/browse/MOB-11426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-11435] Bump iOS SDK to `v11.6.0`

CHANGELOG.md, android/build.gradle, package.json
=> [MOB-11468] Release v11.6.0

CHANGELOG.md, android/native.gradle
=> [MOB-11947] Bump Android SDK to `v11.9.0`

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, package.json
=> [MOB-11949] Release v11.9.0

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, package.json
=> [MOB-12036] Release v11.9.1

android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java, src/modules/Instabug.ts, src/native/NativeInstabug.ts, test/mocks/mockInstabug.ts, test/modules/Instabug.spec.ts
=> [MOB-12043] Remove Android Module Dead Code

.github/stale.yml
=> [MOB-12066] Run Probot Stale only on Issues

cli/UploadSourcemaps.ts, cli/index.ts
=> [MOB-12207] Fix CLI Typos

.github/auto-assign-issues.yml, .github/lock.yml
=> [MOB-12212] Remove Unused GitHub Apps

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
=> [MOB-12237] Release `v11.10.0`

CHANGELOG.md
- Fixes a couple of changelog typos
=> [MOB-12245] Fix Changelog Typos

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
=> [MOB-12435] Release `v11.12.0`

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
=> [MOB-12553] Release v11.13.0

CHANGELOG.md, android/build.gradle, android/jacoco.gradle, android/native.gradle, android/sourcemaps.gradle, examples/default/ios/Podfile.lock, ios/native.rb, package.json
=> [MOB-12553] release/11.13.0

CHANGELOG.md
Fixed a small issue with the PR link of a changelog entry spotted while previewing the file.
Jira ID: MOB-12979
=> fix: update PR link format in changelog

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
Release v11.14.0
Jira ID: [MOB-13021](https://instabug.atlassian.net/browse/MOB-13021)
[MOB-13021]: https://instabug.atlassian.net/browse/MOB-13021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update sdk version to v11.14.0

.circleci/config.yml, scripts/notify-github.sh, scripts/snapshot-branch.sh, scripts/snapshot-comment.md
Add a CI job for generating snapshots out of PRs.
Snapshot name: snapshot/final-final-test
Jira ID: MOB-12896
=> ci: automate snapshot generation

CHANGELOG.md, android/native.gradle
Bump Android sdk to v.12.1.0
Jira ID: [MOB-13052](https://instabug.atlassian.net/browse/MOB-13052)
- #1031 
[MOB-13052]: https://instabug.atlassian.net/browse/MOB-13052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump android sdk v12.1.0

android/src/main/java/com/instabug/reactlibrary/ArgsRegistry.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugAPMModule.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java, examples/default/ios/InstabugTests/InstabugSampleTests.m, ios/RNInstabug/InstabugReactBridge.h, ios/RNInstabug/InstabugReactBridge.m, src/models/ReproConfig.ts, src/modules/Instabug.ts, src/native/NativeInstabug.ts, test/modules/Instabug.spec.ts
Add new session replay argument for repro steps API
Jira ID: [IBGCRASH-20025](https://instabug.atlassian.net/browse/IBGCRASH-20025)
[IBGCRASH-20025]: https://instabug.atlassian.net/browse/IBGCRASH-20025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add new session replay argument for repro steps api

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
- Release `v12.2.0`
[MOB-13247](https://instabug.atlassian.net/browse/MOB-13247)
[MOB-13247]: https://instabug.atlassian.net/browse/MOB-13247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> release: v12.2.0

.circleci/config.yml
Resolve nn releasse job ci issue
- [\[MOB-13252\] \[CP\] \[RN\] Fix NN automatic snapshot release ci - JIRA](https://instabug.atlassian.net/browse/MOB-13252)
=> fix: resolve nn ci issue

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
Release `v12.4.0`
Jira ID: MOB-13346
=> release: v12.4.0

CHANGELOG.md
update changelog.md with the following:
- Add missing date for v12.1.0 - v12.2.0.
- Fix github comparison link of v11.14.0 - v12.1.0.
Jira ID: MOB-13255
[MOB-13255]: https://instabug.atlassian.net/browse/MOB-13255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: update changelog headers for date and compare link fixes

examples/default/ios/Podfile.lock, scripts/dream-11-delete-unused-features
Create Dream11 Customization Script
https://instabug.atlassian.net/browse/MOB-13571
=> chore: create d11 customization script

android/src/main/java/com/instabug/reactlibrary/RNInstabug.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java, examples/default/ios/InstabugTests/InstabugSampleTests.m, examples/default/ios/InstabugTests/RNInstabugTests.m, ios/RNInstabug/InstabugReactBridge.h, ios/RNInstabug/InstabugReactBridge.m, ios/RNInstabug/RNInstabug.h, ios/RNInstabug/RNInstabug.m, src/models/InstabugConfig.ts, src/modules/Instabug.ts, src/native/NativeInstabug.ts, test/modules/Instabug.spec.ts
Support code push 
Jira ID: MOB-13384
=> feat: support code push

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
bump up instabug-reactnative to v12.6.0
Jira ID: MOB-13667
=> release: v12.6.0

CHANGELOG.md
Add missing `support code push` CHANGELOG entry.
Jira ID: MOB-13671
=> docs: add missing entry for `support code push`

CHANGELOG.md
Add missing CHANGELOG entry for `support code push`.
Jira ID: MOB-13671
=> docs: add missing `support code push` changelog entry

.gitignore
Ignore run configurations files for Jetbrains IDEs.
Jira ID: MOB-13736
=> chore(android): ignore jetbrains ide run configurations

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
Bump up instabug-reactnative to `v12.7.0`
Jira ID: MOB-13963
=> release: v12.7.0

CHANGELOG.md, android/src/main/java/com/instabug/reactlibrary/Constants.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java, android/src/test/java/com/instabug/reactlibrary/util/GlobalMocks.java, android/src/test/java/com/instabug/reactlibrary/util/MockReflected.java, examples/default/ios/InstabugTests/InstabugSampleTests.m, ios/RNInstabug/InstabugReactBridge.h, ios/RNInstabug/InstabugReactBridge.m, ios/RNInstabug/Util/Instabug+CP.h, src/modules/Instabug.ts, src/native/NativeInstabug.ts, test/mocks/mockInstabug.ts, test/modules/Instabug.spec.ts
Jira ID: MOB-13737## Description of the change
Re-write the changelog entry for supporting user-steps in Android.
Jira ID: MOB-13966
Jira ID: MOB-13680
=> feat: add network diagnostics callback

CHANGELOG.md, android/native.gradle
=> chore(android): bump sdk to v12.7.1

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
Release `v12.7.1`
Jira ID: MOB-13982
=> release: v12.7.1

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
Release `v12.8.0`
Jira ID: MOB-14053
=> release: v12.8.0

examples/default/android/app/src/main/java/com/instabug/react/example/RNInstabugExampleCrashReportingModule.java
Fix the fatal hangs and ANR crash buttons in the example app.
Jira ID: APM-19536
=> fix(example): fix fatal hangs and ANR crash buttons

examples/default/src/components/VerticalListTile.tsx, examples/default/src/screens/SurveysScreen.tsx
1. show a survey with a token 
2. button to detect if the user has responded to the survey with a token
| Surveys Screen  | 
|-----------|
|![Screenshot_1709047586](https://github.com/Instabug/Instabug-React-Native/assets/154802748/43e52efe-c3f5-4acd-8a80-cb8cc65b5663)|
Jira ID = MOB-13920 , MOB-13921
=> feat(example): survey with token actions

CHANGELOG.md, android/build.gradle, android/native.gradle, android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugSessionReplayModule.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugReactnativeModuleTest.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugSessionReplayModuleTest.java, examples/default/ios/InstabugTests/InstabugSampleTests.m, examples/default/ios/InstabugTests/InstabugSessionReplayTests.m, examples/default/ios/Podfile.lock, examples/default/src/navigation/HomeStack.tsx, examples/default/src/screens/HomeScreen.tsx, examples/default/src/screens/SessionReplayScreen.tsx, ios/RNInstabug/InstabugReactBridge.h, ios/RNInstabug/InstabugReactBridge.m, ios/RNInstabug/InstabugSessionReplayBridge.h, ios/RNInstabug/InstabugSessionReplayBridge.m, package.json, src/modules/Instabug.ts, src/modules/SessionReplay.ts, src/native/NativeInstabug.ts, src/native/NativeSessionReplay.ts, test/mocks/mockInstabug.ts, test/mocks/mockSessionReplay.ts, test/modules/Instabug.spec.ts, test/modules/SessionReplay.spec.ts
Resolve divergence that occurred between dev and master as we had lots of PRs merged into dev, and wanted to release only 2-3 of them in master (publicly and for dream11).
=> chore: resolving divergent branches

CHANGELOG.md, android/native.gradle
chore(android): bump sdk to v12.9.0
JIra ID : [MOB-14178](https://instabug.atlassian.net/browse/MOB-14178)
[MOB-14178]: https://instabug.atlassian.net/browse/MOB-14178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(android): bump sdk to v12.9.0

.circleci/config.yml
ci: add injazat and package new namespace release pipeline
Jira ID : MOB-14187
=> ci: add injazat and package new namespace release pipeline

.circleci/config.yml, CHANGELOG.md, src/modules/Instabug.ts
=> fix: dev -> master merge issue

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
Release v12.9.0
Jira ID: MOB-14177
=> Release: 12.9.0

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
Release v13.0.0
Jira ID: MOB-14360
=> release: v13.0.0

.circleci/config.yml
upload SDK to @instabug/react-native
Jira ID :
=> CI: add new  namespace pipeline 

.circleci/config.yml
Sync `dev` with `master`.
Jira ID: MOB-14569
=> chore: sync `dev` with `master`

CHANGELOG.md, android/native.gradle
Bump Android SDK to v13.0.3
Jira ID: MOB-14566
=> chore(android): bump sdk to v13.0.3

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
Release `v13.0.4`.
Jira ID: MOB-14568
=> release: v13.0.4

CHANGELOG.md, examples/default/ios/Podfile.lock, package.json
Release v13.1.1
JIRA ID: MOB-14360
=> Release:v13.1.1

android/native.gradle, android/src/main/java/com/instabug/reactlibrary/Constants.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugAPMModule.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugAPMModuleTest.java, examples/default/src/screens/ApmScreen.tsx, src/modules/APM.ts, src/modules/Instabug.ts, src/native/NativeAPM.ts, src/utils/FeatureFlags.ts, src/utils/XhrNetworkInterceptor.ts, test/mocks/mockAPM.ts, test/modules/APM.spec.ts
Get W3C feature flags for android 
[JiraID:MOB14515
](https://instabug.atlassian.net/browse/MOB-14515)
=> feat: get w3c feature flags android

CHANGELOG.md
=> Release: v14.0.0 

tsconfig.upload.json
release/v14.0.0-d11-fix-build
JIRA ID :
=> Release: v14.0.0-d11-fix-build

android/native.gradle
Integrate with android v.14.0.2.1
[JiraId:INSD-12543](https://instabug.atlassian.net/browse/INSD-12543)
=> chore(android): integrate with V.14.0.2.1

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
release 14.0.1 for dream11
JIRA ID : INSD-12543
=> release(d11) : 14.0.2

CHANGELOG.md
release:v14.1.0
JIRA ID : MOB-17068
=> Release:v14.1.0

CHANGELOG.md
release: v14.1.0
JIRA ID : MOB-17068
=> Release: v14.1.0

android/src/main/java/com/instabug/reactlibrary/RNInstabugAPMModule.java, ios/RNInstabug/InstabugAPMBridge.m, src/modules/APM.ts
Enhance inline code documentation for APM module.
Jira ID: APM-21632
=> chore: enhance inline code documentation for APM module.

CHANGELOG.md, android/native.gradle, examples/default/ios/Podfile.lock, package.json
release(dream11):14.0.3
JIRA ID :
=> release(dream11):14.0.3

android/native.gradle
> Bump Instabug Android SDK to v14.3.0
- [] Bug fix (non-breaking change that fixes an issue)
- [] New feature (non-breaking change that adds functionality)
=> chore(android): bump sdk to v14.3.0

ios/RNInstabug/InstabugCrashReportingBridge.m
> fix crash on non-fatal crash v.0.77.1 RN
> [Issue links go here](https://instabug.atlassian.net/browse/INSD-13172)
=> fix: crash on non fatal

CHANGELOG.md, android/native.gradle
=> chore: (Android) bump sdk to v14.3.0

CHANGELOG.md, android/build.gradle, examples/default/ios/Podfile.lock, package.json
=> release: 14.3.0

CHANGELOG.md, android/build.gradle, android/native.gradle, examples/default/ios/Podfile.lock, package.json
=> Release: v14.0.4

CHANGELOG.md, scripts/find-token.sh
> Added more search capabilities to the `find-token.sh` script. e.g., searching in .env file for react config.
JIRA ID : INSD-13284
=> feat: fix find token script

CHANGELOG.md, android/src/main/java/com/instabug/reactlibrary/RNInstabug.java, android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java, android/src/test/java/com/instabug/reactlibrary/RNInstabugTest.java, examples/default/ios/InstabugTests/InstabugSampleTests.m, examples/default/ios/Podfile.lock, examples/default/src/App.tsx, ios/RNInstabug/InstabugNetworkLoggerBridge.h, ios/RNInstabug/InstabugNetworkLoggerBridge.m, ios/RNInstabug/InstabugReactBridge.h, ios/RNInstabug/InstabugReactBridge.m, package.json, src/models/InstabugConfig.ts, src/modules/Instabug.ts, src/native/NativeInstabug.ts, src/native/NativeNetworkLogger.ts, test/modules/Instabug.spec.ts, test/utils/InstabugUtils.spec.ts
=> Release : v15.0.2
